version: 1

update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "daily"
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "in_range"
    ignored_updates:
      - match:
          dependency_name: "broccoli-asset-rev"
      - match:
          dependency_name: "ember-ajax"
      - match:
          dependency_name: "ember-cli"
      - match:
          dependency_name: "ember-cli-dependency-checker"
      - match:
          dependency_name: "ember-cli-eslint"
      - match:
          dependency_name: "ember-cli-htmlbars"
      - match:
          dependency_name: "ember-cli-htmlbars-inline-precompile"
      - match:
          dependency_name: "ember-cli-inject-live-reload"
      - match:
          dependency_name: "ember-cli-qunit"
      - match:
          dependency_name: "ember-cli-shims"
      - match:
          dependency_name: "ember-cli-sri"
      - match:
          dependency_name: "ember-cli-uglify"
      - match:
          dependency_name: "ember-disable-prototype-extensions"
      - match:
          dependency_name: "ember-export-application-global"
      - match:
          dependency_name: "ember-load-initializers"
      - match:
          dependency_name: "ember-maybe-import-regenerator"
      - match:
          dependency_name: "ember-resolver"
      - match:
          dependency_name: "ember-source"
      - match:
          dependency_name: "ember-source-channel-url"
      - match:
          dependency_name: "ember-try"
      - match:
          dependency_name: "eslint-plugin-ember"
      - match:
          dependency_name: "eslint-plugin-node"
      - match:
          dependency_name: "loader.js"
      - match:
          dependency_name: "qunit-dom"
